datafile<-read.table("household_power_consumption.txt",sep=";",header=TRUE,dec=".")
pst<-subset(datafile,as.Date(strptime(datafile$Date,format="%d/%m/%Y"))=="2007-02-01" | as.Date(strptime(datafile$Date,format="%d/%m/%Y"))== "2007-02-02")
globalActivePower<-as.numeric(pst$Global_active_power)
datetime <- strptime(paste(pst$Date, pst$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
subMetering1 <- as.numeric(pst$Sub_metering_1)
subMetering2 <- as.numeric(pst$Sub_metering_2)
subMetering3 <- as.numeric(pst$Sub_metering_3)

png("plot3.png", width=480, height=480)
plot(datetime, subMetering1, type="l", ylab="Energy Submetering", xlab="")
lines(datetime, subMetering2, type="l", col="red")
lines(datetime, subMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()
